parameters:
    shop.common.common_controller: Shop\CommonBundle\Controller\CommonController
    shop.common.user_repository: Shop\CommonBundle\Entity\UserRepository

services:
  shop.common.common_controller:
      abstract: true
      class: %shop.common.common_controller%
      calls:
        - [setTemplating, ["@templating"]]

  shop.common.user_repository:
      class: %shop.common.user_repository%
      factory_service: doctrine.orm.entity_manager
      factory_method:  getRepository
      arguments:
          - 'Shop\CommonBundle\Entity\User'
