parameters:
    shop.common.common_controller: Shop\CommonBundle\Controller\CommonController
    shop.common.fixtures_path: %kernel.root_dir%/../src/Shop/CommonBundle/Resources/data/

services:
  shop.common.common_controller:
      abstract: true
      class: %shop.common.common_controller%
      calls:
        - [setTemplating, ["@templating"]]
