shop_security:
    resource: "@ShopSecurityBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

webSite:
    resource: "@WebSiteBundle/Resources/config/routing.yml"
    prefix:   /

login_check:
    pattern:   /admin/login_check
