parameters:
    shop.common.common_controller: Shop\CommonBundle\Controller\CommonController

services:
  shop.website.index_controller:
      class: %shop.website.index_controller%
      parent: shop.common.common_controller
      arguments: ["@templating"]
